services:
  db:
    image: postgres:15
    container_name: telegram_postgres
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASS}
      POSTGRES_DB: ${DB_NAME}
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DB_USER} -d ${DB_NAME}"]
      interval: 5s
      timeout: 5s
      retries: 5
  app:
    build: .
    container_name: telegram_analytics_app
    volumes:
      - .:/app
      - ./profiles.yml:/root/.dbt/profiles.yml
      - ./profiles.yml:/app/profiles.yml  # Fallback for dbt looking in /app
    env_file:
      - .env
    depends_on:
      db:
        condition: service_healthy
    command: bash
    tty: true
volumes:
  pgdata: